AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per Keras Application VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet # image classfication
LEARNING_RATE: 0.01
